### ISSUE TITLE
window html portabilité

### ISSUE THREAD

**Issue by nicolas-voisin** [Hellfire01/MangaScrap#1]
ne peut pas afficher l'html
le chemin part de bash ubuntu et n'est donc pas compatible avec window localement

**Comment by Hellfire01** [comment]
désolé du retard de la réponse, je t'invite à pull, je vais avoir corrigé le problème ce soir.
Le soucis était dut au fait que tous les chemins de chiers étaient absolus et pas locaux.
Maintenant, l'html réagit à la position locale des fichiers.
