### ISSUE TITLE
dir_create(directory) isn't portable on Windows

### ISSUE THREAD

**Issue by AceyT** [Hellfire01/MangaScrap#2]
### Problem
Currently, in files : 
- sources/utils_manga.rb
- sources/utils/utils_file.rb

There is a function named **dir_create**
However, the algorithm isn't portable with Windows

### Fix
After some tests, the solution was to have the `build` variable initialised to *"nothing"* instead of *"/"*

### Proposed solution
Your algorithm generate an empty first element on UNIX paths with the `list = directory.split('/')`, but not on Windows.
Instead of having directly the variable `build` set to a value, you have to do it conditionally base on your first element in `list`

Wich gives us the following functions :
```ruby
def dir_create(directory)
  if directory[0, 1] == '~'
    directory['~'] = Dir.home
  end
  unless Dir.exist?(directory)
    puts directory + ' does not exist, creating it'
    list = directory.split('/')
    if list[0].empty?
      build = '/'
    else
      build = ""
    end
    list = list.reject {|elem| elem.empty?}
    list.each do |elem|
      build += elem + '/'
      unless Dir.exist?(build)
        Dir.mkdir(build)
      end
    end
  end
end

```

I didn't do a Pull Request because I don't know Ruby, and I deduced this syntax through analysing your code and testing it with `irb` and modified said files for checking that it would work.

**Comment by Hellfire01** [comment]
thanks a lot, I will use it in the next stable version

**Comment by Hellfire01** [comment]
will implement it in 0.11.1
